---
- name: reload systemd daemon
  systemd:
    daemon_reload: yes

- name: reload nginx
  systemd:
    name: nginx
    state: reloaded

- name: restart nginx
  systemd:
    name: nginx
    state: restarted

- name: reload firewalld
  systemd:
    name: firewalld
    state: reloaded